### ISSUE TITLE
Default dpi

### ISSUE THREAD

**Issue by shizacat** [amenezes/aiopytesseract#3]
### Need/Ideas Statement

Next )
Exists yet problem.

Tesseract by default not need dpi, then it will be tried to select appropriate dpi himself.

```bash
# man tesseract
--dpi N
           Specify the resolution N in DPI for the input image(s). A typical value for N is 300. Without this option, the resolution is read from the metadata
           included in the image. If an image does not include that information, Tesseract tries to guess it.
```

This is not possible in your implementation. The value for 'dpi' always has something value.
May be change it? If need I may create PR )

**Comment by amenezes** [comment]
Hello again @shizacat.

I purposely fixed the DPI option. I've had some problems with default option on tesseract-ocr v4, so I thought I'd use a default value maybe to provide a better result or even to try follow the resizing suggested in the [documentation](https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#rescaling), although the current value is 200 and the wrapper do not perform any type of treatment in the image provided.

Do you have any specific needs or would it be a suggestion to leave the wrapper in greater compliance with tesseract-ocr?

**Comment by shizacat** [comment]
@amenezes, Helleo!
No, I don't have specific require, I need recognize documents. But when I was checking different options for recognize, tried to find better configuration, this library I don't have possibility to make it.
But, same tesseract is had it feature. I think will be better to stay this feature.

If you need default value, may be to do: if value dpi is None, don't set him.
What do you tell?
Only into one place is needed to change: '_build_cmd_args' ;)

**Comment by amenezes** [comment]
@shizacat, sorry for delay.

Let's wait a little longer to make this adjustment, at least until there is a real need.

As I commented with you I have noticed several warnings regarding the use of the features in standard mode. I have used latest release to process more than 1M page per week without any problem.

**Comment by shizacat** [comment]
@amenezes, don't worry about this.
Ok, as you decide.
