### ISSUE TITLE
got nothing string output

### ISSUE THREAD

**Issue by thedtvn** [amenezes/aiopytesseract#6]
### Platform

Linux

### Steps to Reproduce

1  install
2 add to code 
3 run 
4 get nothing

### Expected Result

get some text output

### Actual Result

![image](https://user-images.githubusercontent.com/80153297/229539622-27c2712c-cae7-49fc-adbc-77c9127a88b7.png)
![image](https://user-images.githubusercontent.com/80153297/229540253-4c47c80a-dbb2-4278-bfcc-8e10ed2f83d7.png)
when using tesseract
![image](https://user-images.githubusercontent.com/80153297/229539854-36214545-3050-4165-99cf-add29c4e8395.png)

**Comment by amenezes** [comment]
@thedtvn,

Really sorry for delay.

Could you try execute this code in DEBUG mode, for example:

```python
import logging

import aiopytesseract


logging.basicConfig(level=logging.DEBUG)
# DEBUG:aiopytesseract:aiopytesseract command: 'tesseract stdin stdout --dpi 300 --psm 3 --oem 3 -l eng txt'
aiopytesseract.image_to_string('tests/samples/file-sample_150kB.png')
'Lorem ipsum\n\nLorem ipsum dolor sit amet, consectetur adipiscing\nelit. Nunc ac faucibus odio.\n'
```

Copy the command and execute in another terminal
```bash
cat tests/samples/sample_150kB.png | tesseract stdin stdout --dpi 300 --psm 3 --oem 3 -l eng txt
Lorem ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing
elit. Nunc ac faucibus odio.
```
What's your output? It was as expected?

**Comment by thedtvn** [comment]
some random char and nuber to bypass capcha

**Comment by amenezes** [comment]
I think that you need include some step to pre-process image before submit to Tesseract. Try something like:

- pypillowfight: https://gitlab.gnome.org/World/OpenPaperwork/libpillowfight
- scikit-image: https://scikit-image.org

**Comment by thedtvn** [comment]
> I think that you need include some step to pre-process image before submit to Tesseract. Try something like:
> 
> 
> 
> - pypillowfight: https://gitlab.gnome.org/World/OpenPaperwork/libpillowfight
> 
> - scikit-image: https://scikit-image.org

ye i think so
