### ISSUE TITLE
image_to_data psm and output_type

### ISSUE THREAD

**Issue by piotr-sikora-v** [amenezes/aiopytesseract#7]
### Need/Ideas Statement

Hi, 
Thanks for sharing this code!

There is any option to add this two parameters to `image_to_data` function?

Best regards!

**Comment by amenezes** [comment]
Hello @piotr-sikora-v,

Currently the option `psm` is not available. I will try add support for this feature.

Maybe `output_type` option it's not necessary beacuse `image_to_data` returns a Data object that is a [dataclass](https://docs.python.org/3/library/dataclasses.html) so can you use or convert to any intermediate format. Anyway, let me know if there any specific behaviors I've missed.

**Comment by amenezes** [comment]
@piotr-sikora-v,

Can you try `image_to_data` method from the branch [`rl-0.12.0`](https://github.com/amenezes/aiopytesseract/tree/rl-0.12.0). I added `psm` option to method.

``` py
async def image_to_data(
    image: Any,
    dpi: int = AIOPYTESSERACT_DEFAULT_DPI,
    lang: str = AIOPYTESSERACT_DEFAULT_LANGUAGE,
    timeout: float = AIOPYTESSERACT_DEFAULT_TIMEOUT,
    encoding: str = AIOPYTESSERACT_DEFAULT_ENCODING,
    tessdata_dir: Optional[str] = None,
    psm: int = AIOPYTESSERACT_DEFAULT_PSM,
) -> List[Data]:
    """Information about boxes, confidences, line and page numbers.

    :param image: image input to tesseract. (valid values: str, bytes)
    :param dpi: image dots per inch (DPI). (default: 300)
    :param lang: tesseract language. (default: eng, format: eng, eng+por, eng+por+fra)
    :param timeout: command timeout (default: 30)
    :param encoding: decode bytes to string. (default: utf-8)
    :param tessdata_dir: location of tessdata path. (default: None)
    :param psm: page segmentation modes. (default: 3)
    """
```

**Comment by amenezes** [comment]
@piotr-sikora-v,

I'm shared a new version - 0.12.0 - with support to `psm` in the function `image_to_data`. So I will close this issue, but let me know if you need something.
