### ISSUE TITLE
Char Whitelist support

### ISSUE THREAD

**Issue by WhyDoWeLiveWithoutMeaning** [amenezes/aiopytesseract#8]
### Need/Ideas Statement

It would be nice to have access to `tessedit_char_whitelist` so that I can whitelist only specific characters.

**Comment by amenezes** [comment]
@WhyDoWeLiveWithoutMeaning,

The feature is available in version 0.14.0.

So now can you use:

``` python
from pathlib import Path

import aiopytesseract

await aiopytesseract.image_to_string(
	"tests/samples/text-with-chars-and-numbers.png",
	config=[("tessedit_char_whitelist", "0123456789")]
)
```
